Universe = Vanilla
GEOM = MAIA_v0/MAIA_v0_vacuum.xml
TAG  = vacuum

Executable = run_sim.sh
Arguments = $(Process) photonGun_E_25.slcio sim_$(Tag)_$(Process).slcio $(GEOM)



should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $ENV(HOME)/mucoll/.setup_shower_profiles.sh, $ENV(HOME)/mucoll/gen/photonGun_E_25.slcio, $ENV(HOME)/mucoll/SteeringMacros/k4Reco/sim_steer_condor.py $ENV(HOME)/mucoll/k4geo/MuColl/MAIA/compact/MAIA_v0

# --- outputs ---
transfer_output_files = sim_$(TAG)_$(Process).slcio
transfer_output_remaps = "sim_$(TAG)_$(Process).slcio = output/sim_$(TAG)_$(Process).slcio"

# --- logs ---
output = logs/$(TAG)_$(Cluster)_$(Process).out
error  = logs/$(TAG)_$(Cluster)_$(Process).err
log    = logs/$(TAG)_$(Cluster).log

# --- resources (tune from a test job) ---
request_cpus   = 1
request_memory = 4GB
request_disk   = 4GB
+JobDurationCategory = "Medium"

queue 50
