Universe = container 
container_image = /cvmfs/unpacked.cern.ch/ghcr.io/muoncollidersoft/mucoll-sim-ubuntu24:v2.11-amd64
requirements = HAS_CVMFS_unpacked_cern_ch == True

GEOM = MAIA_v0/MAIA_v0_vacuum.xml
TAG  = vacuum

Executable = run_sim.sh
Arguments = $(Process) photonGun_E_25.slcio sim_$(Tag)_$(Process).slcio $(GEOM)

# --- inputs ---
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $ENV(HOME)/mucoll/gen/photonGun_E_25.slcio, $ENV(HOME)/mucoll/SteeringMacros/Sim/sim_steer_GEN_CONDOR.py, $ENV(HOME)/mucoll/k4geo/MuColl/MAIA/compact/MAIA_v0/

# --- outputs ---
transfer_output_files = sim_$(TAG)_$(Process).slcio
transfer_output_remaps = "sim_$(TAG)_$(Process).slcio = output/sim_$(TAG)_$(Process).slcio"

# --- logs ---
output = logs/$(TAG)_$(Cluster)_$(Process).out
error  = logs/$(TAG)_$(Cluster)_$(Process).err
log    = logs/$(TAG)_$(Cluster).log

# --- resources (tune from a test job) ---
request_cpus   = 1
request_memory = 4GB
request_disk   = 4GB
+JobDurationCategory = "Medium"

queue 1 
